# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=2048)),
                ('pogo_id', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image_url', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GymNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField()),
                ('nickname', models.CharField(max_length=2048)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicknames', to='raidikalu.Gym')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField()),
                ('tier', models.PositiveSmallIntegerField(default=0)),
                ('pokemon', models.CharField(blank=True, max_length=255)),
                ('fast_move', models.CharField(blank=True, max_length=255)),
                ('charge_move', models.CharField(blank=True, max_length=255)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raids', to='raidikalu.Gym')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaidVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField()),
                ('submitter', models.CharField(max_length=255)),
                ('vote_field', models.CharField(choices=[('tier', 'Tier'), ('pokemon', 'Pokémon'), ('fast_move', 'Fast move'), ('charge_move', 'Charge move'), ('start_at', 'Starting time')], max_length=255)),
                ('vote_value', models.CharField(max_length=255)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raidikalu.DataSource')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='raidikalu.Raid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField()),
                ('submitter', models.CharField(max_length=255)),
                ('attendee_count', models.PositiveSmallIntegerField(default=1)),
                ('estimated_arrival_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_arrived', models.BooleanField(default=False)),
                ('has_finished', models.BooleanField(default=False)),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='raidikalu.Raid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
