# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='pokemon',
            new_name='pokemon_name',
        ),
        migrations.AddField(
            model_name='raid',
            name='pokemon_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='tier',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
