# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0002_added_pokemon_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('raid_types_json', models.TextField()),
            ],
        ),
    ]
