# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0003_editablesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablesettings',
            name='notifications_json',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
