# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0005_raid_submitter_and_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='is_park',
            field=models.BooleanField(default=False),
        ),
    ]
