# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0006_gym_is_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablesettings',
            name='additional_information',
            field=models.TextField(blank=True),
        ),
    ]
