# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0007_editablesettings_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='latest_ex_raid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
