# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0008_gym_latest_ex_raid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='s2_cell_eligible_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='s2_cell_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='s2_cell_nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
