# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0009_gym_s2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raidikalu.DataSource'),
        ),
        migrations.AddField(
            model_name='raid',
            name='verified_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
