# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0010_raid_verification_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='verified_text',
            new_name='unverified_text',
        ),
    ]
