# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0011_rename_verification_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='latest_ex_raid_at',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='s2_cell_eligible_count',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='s2_cell_id',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='s2_cell_nickname',
        ),
        migrations.AddField(
            model_name='gym',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='raidvote',
            name='vote_field',
            field=models.CharField(choices=[('tier', 'Taso'), ('pokemon_name', 'Monni'), ('fast_move', 'Fast move'), ('charge_move', 'Charge move'), ('start_at', 'Alkamisaika')], max_length=255),
        ),
    ]
