# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-22 10:56
from __future__ import unicode_literals

import json
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


def editable_settings_data_migration(apps, schema_editor):
    EditableSettings = apps.get_model('raidikalu', 'EditableSettings')

    def load_current_settings():
        try:
            return EditableSettings.objects.filter(expires_at__gt=timezone.now()).earliest('expires_at')
        except EditableSettings.DoesNotExist:
            pass
        try:
            return EditableSettings.objects.latest('expires_at')
        except EditableSettings.DoesNotExist:
            pass
        return EditableSettings.objects.create(**{
            'expires_at': timezone.now(),
            'raid_types_json': '[]',
        })

    editable_settings = load_current_settings()
    editable_settings_raid_types = json.loads(editable_settings.raid_types_json)

    RaidType = apps.get_model('raidikalu', 'RaidType')
    for raid_type_dict in editable_settings_raid_types:
        raid_type_obj = RaidType(tier=raid_type_dict['tier'], monster_name=raid_type_dict['pokemon'])
        raid_type_obj.save()

    InfoBox = apps.get_model('raidikalu', 'InfoBox')
    InfoBox.objects.create(content=editable_settings.additional_information)


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0012_remove_s2_stuff_add_is_active_for_gyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField()),
                ('monster_name', models.CharField(max_length=255)),
                ('monster_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='raid',
            old_name='pokemon_name',
            new_name='monster_name',
        ),
        migrations.RemoveField(
            model_name='raid',
            name='pokemon_number',
        ),
        migrations.AlterField(
            model_name='raidvote',
            name='vote_field',
            field=models.CharField(choices=[('tier', 'Taso'), ('monster_name', 'Monni'), ('fast_move', 'Fast move'), ('charge_move', 'Charge move'), ('start_at', 'Alkamisaika')], max_length=255),
        ),
        migrations.AddField(
            model_name='raid',
            name='raid_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raids', to='raidikalu.RaidType'),
        ),
        migrations.RunPython(editable_settings_data_migration),
        migrations.DeleteModel(
            name='EditableSettings',
        ),
    ]
