# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0013_refactor_editable_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='is_park',
            new_name='is_ex_eligible',
        ),
        migrations.AlterField(
            model_name='raidvote',
            name='vote_field',
            field=models.CharField(choices=[('tier', 'Tier'), ('monster_name', 'Raid boss'), ('fast_move', 'Fast move'), ('charge_move', 'Charge move'), ('start_at', 'Starting time')], max_length=255),
        ),
    ]
