# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0015_add_raid_type_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raidtype',
            options={'ordering': ['-tier', '-priority']},
        ),
        migrations.AlterField(
            model_name='raid',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raids', to='raidikalu.Gym', unique=True),
        ),
    ]
